package dev.md3ui.tools;

import dev.md3ui.core.color.Argb;
import dev.md3ui.core.gfx.Md3Canvas;

import java.awt.image.BufferedImage;
import java.util.ArrayDeque;
import java.util.Deque;

/**
 * {@link Md3Canvas} backed by a {@code BufferedImage}.
 *
 * <p>This is how the repository screenshots are produced. The widgets do not
 * know which backend they are drawing into, so the PNGs are generated by the
 * same layout and painting code that runs in the game &mdash; not a mockup that
 * can drift away from the implementation.
 *
 * <p>Text is drawn with an embedded 5x7 bitmap font rather than AWT's font
 * rasteriser, so output is deterministic across machines (a CI runner has
 * different fonts installed than a dev box) and visually close to Minecraft's
 * own fixed-width glyph metrics.
 */
public final class RasterCanvas implements Md3Canvas {

    private final BufferedImage image;
    private final int[] pixels;
    private final int w, h;

    private static final class Clip {
        final float x, y, w, h;
        Clip(float x, float y, float w, float h) { this.x = x; this.y = y; this.w = w; this.h = h; }
    }

    private final Deque<Clip> clips = new ArrayDeque<>();
    private final Deque<float[]> transforms = new ArrayDeque<>(); // {dx, dy, scale, ox, oy}
    private final Deque<Float> alphas = new ArrayDeque<>();

    /** Supersampling factor: draw at NxN then downscale for clean edges. */
    private final int ss;

    public RasterCanvas(int width, int height, int supersample) {
        this.ss = Math.max(1, supersample);
        this.w = width * ss;
        this.h = height * ss;
        this.image = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        this.pixels = ((java.awt.image.DataBufferInt) image.getRaster().getDataBuffer()).getData();
        transforms.push(new float[] {0, 0, 1, 0, 0});
        alphas.push(1f);
    }

    public int logicalWidth() { return w / ss; }
    public int logicalHeight() { return h / ss; }

    /** Downscaled result with a box filter, which is where antialiasing comes from. */
    public BufferedImage result() {
        if (ss == 1) return image;
        int ow = w / ss, oh = h / ss;
        BufferedImage out = new BufferedImage(ow, oh, BufferedImage.TYPE_INT_ARGB);
        for (int y = 0; y < oh; y++) {
            for (int x = 0; x < ow; x++) {
                long a = 0, r = 0, g = 0, b = 0;
                for (int sy = 0; sy < ss; sy++) {
                    for (int sx = 0; sx < ss; sx++) {
                        int p = pixels[(y * ss + sy) * w + (x * ss + sx)];
                        int pa = (p >>> 24) & 0xFF;
                        a += pa;
                        r += ((p >> 16) & 0xFF) * pa;
                        g += ((p >> 8) & 0xFF) * pa;
                        b += (p & 0xFF) * pa;
                    }
                }
                int n = ss * ss;
                int oa = (int) (a / n);
                int or = a == 0 ? 0 : (int) (r / a);
                int og = a == 0 ? 0 : (int) (g / a);
                int ob = a == 0 ? 0 : (int) (b / a);
                out.setRGB(x, y, Argb.of(oa, or, og, ob));
            }
        }
        return out;
    }

    // --- Transform helpers ---

    private float[] tf() { return transforms.peek(); }

    private float tx(float x) {
        float[] t = tf();
        return (t[3] + (x + t[0] - t[3]) * t[2]) * ss;
    }

    private float ty(float y) {
        float[] t = tf();
        return (t[4] + (y + t[1] - t[4]) * t[2]) * ss;
    }

    private float ts(float v) { return v * tf()[2] * ss; }

    private float alpha() { return alphas.peek(); }

    // --- Md3Canvas ---

    @Override
    public void fillRect(float fx, float fy, float fw, float fh, int argb) {
        int a = Argb.a(argb);
        if (a == 0 || fw <= 0 || fh <= 0) return;
        int col = Argb.scaleAlpha(argb, alpha());
        if (Argb.a(col) == 0) return;

        float x0 = tx(fx), y0 = ty(fy);
        float x1 = x0 + ts(fw), y1 = y0 + ts(fh);

        Clip c = clips.peek();
        if (c != null) {
            float cx0 = tx(c.x), cy0 = ty(c.y);
            float cx1 = cx0 + ts(c.w), cy1 = cy0 + ts(c.h);
            x0 = Math.max(x0, cx0); y0 = Math.max(y0, cy0);
            x1 = Math.min(x1, cx1); y1 = Math.min(y1, cy1);
        }

        int ix0 = Math.max(0, (int) Math.floor(x0));
        int iy0 = Math.max(0, (int) Math.floor(y0));
        int ix1 = Math.min(w, (int) Math.ceil(x1));
        int iy1 = Math.min(h, (int) Math.ceil(y1));
        if (ix0 >= ix1 || iy0 >= iy1) return;

        for (int y = iy0; y < iy1; y++) {
            // Vertical coverage of this pixel row.
            float covY = Math.min(y + 1f, y1) - Math.max((float) y, y0);
            if (covY <= 0) continue;
            int row = y * w;
            for (int x = ix0; x < ix1; x++) {
                float covX = Math.min(x + 1f, x1) - Math.max((float) x, x0);
                if (covX <= 0) continue;
                float cov = covX * covY;
                int src = cov >= 0.999f ? col : Argb.scaleAlpha(col, cov);
                pixels[row + x] = Argb.over(src, pixels[row + x]);
            }
        }
    }

    @Override
    public void fillGradientV(float x, float y, float fw, float fh, int top, int bottom) {
        int rows = Math.max(1, (int) Math.ceil(fh));
        for (int i = 0; i < rows; i++) {
            float t = rows == 1 ? 0 : i / (float) (rows - 1);
            fillRect(x, y + i, fw, 1f, Argb.lerp(top, bottom, t));
        }
    }

    @Override
    public float drawText(String text, float x, float y, int argb, boolean shadow) {
        if (text == null || text.isEmpty()) return 0;
        float cx = x;
        if (shadow) {
            drawTextPlain(text, x + 0.5f, y + 0.5f, Argb.scaleAlpha(0xFF000000, 0.45f));
        }
        drawTextPlain(text, cx, y, argb);
        return textWidth(text);
    }

    private void drawTextPlain(String text, float x, float y, int argb) {
        float cx = x;
        for (int i = 0; i < text.length(); i++) {
            char ch = text.charAt(i);
            byte[] glyph = BitmapFont.glyph(ch);
            int gw = BitmapFont.width(ch);
            for (int gy = 0; gy < BitmapFont.HEIGHT; gy++) {
                int bits = glyph[gy] & 0xFF;
                for (int gx = 0; gx < gw; gx++) {
                    if ((bits & (1 << (BitmapFont.CELL_W - 1 - gx))) != 0) {
                        fillRect(cx + gx, y + gy, 1f, 1f, argb);
                    }
                }
            }
            cx += gw + 1;
        }
    }

    @Override
    public float textWidth(String text) {
        if (text == null) return 0;
        float total = 0;
        for (int i = 0; i < text.length(); i++) {
            total += BitmapFont.width(text.charAt(i)) + 1;
        }
        return Math.max(0, total - 1);
    }

    @Override
    public float lineHeight() { return BitmapFont.HEIGHT; }

    @Override
    public void pushClip(float x, float y, float cw, float ch) {
        Clip cur = clips.peek();
        if (cur == null) {
            clips.push(new Clip(x, y, cw, ch));
        } else {
            float nx = Math.max(cur.x, x), ny = Math.max(cur.y, y);
            float nx1 = Math.min(cur.x + cur.w, x + cw);
            float ny1 = Math.min(cur.y + cur.h, y + ch);
            clips.push(new Clip(nx, ny, Math.max(0, nx1 - nx), Math.max(0, ny1 - ny)));
        }
    }

    @Override
    public void popClip() { if (!clips.isEmpty()) clips.pop(); }

    @Override
    public void pushTranslate(float dx, float dy) {
        float[] t = tf();
        transforms.push(new float[] {t[0] + dx, t[1] + dy, t[2], t[3], t[4]});
    }

    @Override
    public void pushScale(float ox, float oy, float scale) {
        float[] t = tf();
        transforms.push(new float[] {t[0], t[1], t[2] * scale, ox, oy});
    }

    @Override
    public void popTransform() { if (transforms.size() > 1) transforms.pop(); }

    @Override
    public void pushAlpha(float a) { alphas.push(alpha() * Argb.clamp01(a)); }

    @Override
    public void popAlpha() { if (alphas.size() > 1) alphas.pop(); }

    @Override
    public float width() { return w / (float) ss; }

    @Override
    public float height() { return h / (float) ss; }
}
